version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db.bcosxkxwyazmzlcndhza.supabase.co:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=[YOUR-PASSWORD]
      - DDL_AUTO=update
      - CORS_ALLOWED_ORIGINS=http://localhost:19000
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
    networks:
      - lamusic-network

networks:
  lamusic-network:
    driver: bridge
