version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}?prepareThreshold=0
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DDL_AUTO=update
      - CORS_ALLOWED_ORIGINS=http://localhost:19000
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0

    networks:
      - lamusic-network

networks:
  lamusic-network:
    driver: bridge
