version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/laMusic
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysqlroot
      - DDL_AUTO=update
      - CORS_ALLOWED_ORIGINS=http://localhost:19000
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lamusic-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: laMusic
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - lamusic-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:


networks:
  lamusic-network:
    driver: bridge
